language: ruby
cache: bundler
sudo: false
matrix:
  fast_finish: true
  include:
    - rvm: 2.4
    - rvm: 2.5
    - rvm: 2.6
    - rvm: 2.7
    - rvm: 3.0
    - rvm: jruby-9.2
    - rvm: jruby-head
    - rvm: truffleruby-head
 # ppc64le support code
    - rvm: 2.4
      arch: ppc64le
    - rvm: 2.5
      arch: ppc64le
    - rvm: 2.6
      arch: ppc64le
    - rvm: 2.7
      arch: ppc64le
    - rvm: 3.0
      arch: ppc64le
    - rvm: jruby-9.2
      arch: ppc64le
    - rvm: jruby-head
      arch: ppc64le
  allow_failures:
    - rvm: jruby-head
    - rvm: truffleruby-head
    - rvm: jruby-head
      arch: ppc64le
notifications:
  email: false
